---

- name: Ensure elknet is created
  docker_network:
    name: elknet

- name: Ensure esdata is created
  docker_volume:
    name: esdata

- name: Ensure kbdata is created
  docker_volume:
    name: kbdata

- name: Running elasticsearch
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    restart_policy: on-failure
    restart_retries: 5
    volumes:
      - esdata:/usr/share/elasticsearch/data
    env:
      MAX_MAP_COUNT: "262144"
      cluster.name: es-cluster
      discovery.type: single-node
    networks:
      - name: elknet

- name: Running kibana
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.2
    env:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    volumes:
      - kbdata:/user/share/kibana/config/kibana.yml
    networks:
      - name: elknet

- name: Running logstash
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:6.4.3
    env:
      STDOUT: "true"
    command: 'logstash -e "input { udp { port => 5000 } } output { elasticsearch { hosts => elasticsearch } }"'
    networks:
      - name: elknet

- name: Running logspout
  docker_container:
    name: logspout
    image: gliderlabs/logspout
    restart_policy: always
    command: 'udp://logstash:5000'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - name: hifuminet
      - name: elknet
