version: "3.5"
services:
  bot:
    container_name: hifumi
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://mongo/hifumi
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - hifuminet
  mongo:
    container_name: hifumi_mongo
    image: mongo
    networks:
      - hifuminet
    volumes:
      - ./data/db:/data/db
  mongo-express:
    image: mongoclient/mongoclient
    container_name: mongo-client
    restart: always
    networks:
      - hifuminet
    environment:
      MONGO_URL: mongodb://mongo/hifumi
      MONGOCLIENT_AUTH: "true"
      MONGOCLIENT_USERNAME: hifumi
      MONGOCLIENT_PASSWORD: test
    depends_on:
      - mongo
    ports:
      - 3001:3000
networks:
  hifuminet:
    name: hifuminet
