# development compose file
version: "3.5"
services:
  mongo:
    container_name: hifumi_mongo
    image: mongo
    networks:
      - hifuminet
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    networks:
      - hifuminet
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    ports:
      - 8081:8081
networks:
  hifuminet:
    name: hifuminet
