version: "3.5"
services:
  bot:
    container_name: hifumi
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    networks:
      - hifuminet
    command: npm run dev
    stdin_open: true
    tty: true
  mongo:
    container_name: hifumi_mongo
    image: mongo
    networks:
      - hifuminet
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
networks:
  hifuminet:
