name:                newgame
version:             0.1.0.0
github:              "xetera/newgame"
license:             BSD3
author:              "Xetera"
maintainer:          "@"
copyright:           "2018 Xetera"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/untitled#readme>

dependencies:
  - base >= 4.7 && < 5
  - async
  - http-conduit
  - aeson
  - lens-aeson
  - bytestring
  - text
  - cache
  - hashable
  - clock
  - lens
  - scotty
  - wai-extra
  - wai-middleware-static
  - wai-cors
  - wai

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  newgame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - newgame

tests:
  newgame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - newgame
