version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - yun-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Install executable
          command: stack install --only-dependencies -j4
      - save_cache:
          name: Cache Dependencies
          key: yun-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - ".stack"
            - ".stack-work"
      - persist_to_workspace:
          root: .
          paths: .
  push_container:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t moedevs/yun:latest .
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push moedevs/yun:latest
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - push_container:
          filters:
            branches:
              only: master
          requires:
            - build
