version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: hifumi-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - save_cache:
          paths:
            - ~/.m2
          key: hifumi-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install tslint
      - run: npm run lint
  build_image:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t moedevs/hifumi:latest .
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push moedevs/hifumi:latest

  deploy:
    docker:
      - image: circleci/python:3.6.2-stretch
        environment:
          ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Install dependencies
          command: |
            sudo pip install ansible
            sudo apt update
      - run: echo "$ANSIBLE_PASS" >> .deploy/secret.txt && ansible-playbook --vault-password-file .deploy/secret.txt -b .deploy/start.yaml -i "root@$HOST_IP,"
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - lint
      - build_image:
          filters:
            branches:
              only: master
          requires:
            - build
            - lint
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build_image
