version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: hifumi-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - ~/.m2
          key: hifumi-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run: npm run lint
  build_image:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t moedevs/hifumi:latest .
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push moedevs/hifumi:latest
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - build_image:
          filters:
            branches:
              only: master
          requires:
            - build
