---
- include_vars: secret.yaml

- name: Ensure docker is installed
  pip:
    name:
      - docker

- name: Ensure hifuminet is created
  docker_network:
    name: hifuminet

- name: Creating datadog-agent
  docker_container:
    name: datadog-client
    image: datadog/agent:latest
    log_driver: fluentd
    env:
      DD_API_KEY: "{{ lookup('env', 'DATADOG_API_KEY') }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - name: hifuminet

- name: Creating database
  docker_container:
    name: postgres
    image: postgres
    env:
      POSTGRES_PASSWORD: "{{ postgres.password }}"
      POSTGRES_USER: "{{ postgres.user }}"
      POSTGRES_DB: "{{ postgres.database }}"
    volumes:
      - ./data/db:/data/db
    networks:
      - name: hifuminet

- name: Creating hasura
  docker_container:
    name: hasura
    image: moedevs/hasura
    env:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://{{ postgres.user }}:{{ postgres.password }}@postgres:5432/{{ postgres.database }}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "{{ hasura.admin_secret }}"
    ports:
      - 8080:8080
    networks:
      - name: hifuminet

- name: Updating hifumi's image
  docker_container:
    name: hifumi
    image: moedevs/hifumi
    log_driver: fluentd
    pull: yes
    env:
      TOKEN: "{{  lookup('env', 'TOKEN')  }}"
      PREFIX: $
      OWNERS: "{{ lookup('env', 'OWNERS') }}"
      DATADOG_API_KEY: "{{  lookup('env', 'DATADOG_API_KEY')  }}"
      DATABASE_URL: mongodb://mongo/hifumi
      NODE_ENV: production
    networks:
      - name: hifuminet
