---
- name: Setup caddy
  docker_container:
    name: caddy
    image: moedevs/caddy
    log_driver: "json-file"
    env:
      CADDYPATH: /etc/caddycerts
    ports:
      - 2015:2015
      - 443:443
      - 80:80
    volumes:
      - "{{ lookup('env', 'HOME') }}/.caddy:/etc/caddycerts"

